-- ============================================================
-- Linda1 完整复刻 · Supabase 数据库初始化脚本
-- 在 Supabase 控制台 → SQL Editor 中整段粘贴执行一次即可
-- 说明：沿用项目现状，所有表 RLS 关闭（双人私密空间，公开 anon 读写）
-- ============================================================

-- 1. 朋友圈表（对应 Linda1 的 moments 集合）
create table if not exists public.moments (
  id          bigint generated by default as identity primary key,
  content     text not null default '',
  images      jsonb not null default '[]'::jsonb,   -- 图片地址数组（dataURL）
  sender      text not null,                        -- user_a / user_b
  nickname    text not null default '',
  avatar      text not null default '',             -- 头像图片地址
  likes       jsonb not null default '[]'::jsonb,   -- 点赞人昵称数组
  comments    jsonb not null default '[]'::jsonb,   -- [{nickname, content}]
  create_time bigint not null                       -- 毫秒时间戳
);
alter table public.moments disable row level security;
grant all on public.moments to anon, authenticated;
create index if not exists idx_moments_create_time on public.moments (create_time desc);

-- 2. 恋爱清单打卡表（对应 Linda1 的 couple_tasks 集合）
create table if not exists public.couple_tasks (
  id          bigint generated by default as identity primary key,
  task_id     int not null,                         -- 任务索引 0~99
  title       text not null default '',
  image_url   text not null default '',             -- 打卡照片（dataURL）
  create_time bigint not null,
  writer      text not null default 'unknown'       -- user_a / user_b
);
alter table public.couple_tasks disable row level security;
grant all on public.couple_tasks to anon, authenticated;
create index if not exists idx_couple_tasks_task_id on public.couple_tasks (task_id);

-- 3. 戳一戳表（对应 Linda1 的 love_poke 集合）
create table if not exists public.love_poke (
  id          bigint generated by default as identity primary key,
  sender      text not null,                        -- user_a / user_b
  create_time bigint not null,
  is_read     boolean not null default false
);
alter table public.love_poke disable row level security;
grant all on public.love_poke to anon, authenticated;
create index if not exists idx_love_poke_unread on public.love_poke (sender, is_read);

-- 4. 心情日历表扩展（对应 Linda1 的 love_diary 结构）
--    原 diaries 表已有：id / author / mood / content / created_at
alter table public.diaries add column if not exists date_str text;      -- YYYY-MM-DD
alter table public.diaries add column if not exists images  jsonb default '[]'::jsonb;
alter table public.diaries add column if not exists writer  text;
create index if not exists idx_diaries_date_str on public.diaries (date_str);

-- 5. 聊天表无需改动：图片消息直接以 dataURL 存入 content，
--    读取端按 content 是否以 data:image/ 开头判断为图片消息。
